import os
import requests
import json

def get_ai_intel(topic):
    print(f"Executing AI Intelligence Gathering for: {topic}")
    # গিটহাব সার্ভার থেকে উইকিপিডিয়া বা ওপেন সোর্স ডাটা সংগ্রহ
    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{topic.replace(' ', '_')}"
    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            return response.json().get('extract', 'No detailed info found.')
    except:
        return "Connection to Open Source Data Failed."
    return "Data Not Found."

def save_to_portfolio(topic, data):
    # এটি আপনার পোর্টফোলিওতে একটি নতুন রিসার্চ ফাইল তৈরি করবে
    filename = f"research_{topic.lower()}.md"
    content = f"# AI Research: {topic}\n\n## Data Collected:\n{data}\n\n*Generated by Nobab Bils Dev AI Empire*"
    
    with open(filename, "w") as f:
        f.write(content)
    print(f"Successfully saved {filename}")

if __name__ == "__main__":
    # আমরা এখন একটি লিস্ট দিয়ে দিচ্ছি যা আপনার ১০০০ বট অটো-রিসার্চ করবে
    targets = ["Cybersecurity", "Artificial Intelligence", "Full Stack Development"]
    
    for mission in targets:
        intelligence = get_ai_intel(mission)
        save_to_portfolio(mission, intelligence)
